DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL UNIQUE
);

CREATE TABLE users
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    login TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL CHECK (char_length(password_hash) > 0),
    role_id BIGINT NOT NULL REFERENCES roles(id)
);

CREATE TABLE states
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL UNIQUE
);

CREATE TABLE categories
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL UNIQUE
);

CREATE TABLE items
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item TEXT NOT NULL CHECK (char_length(item) > 0),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    state_id BIGINT NOT NULL REFERENCES states(id),
    category_id BIGINT NOT NULL REFERENCES categories(id),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE comments
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    comment TEXT NOT NULL CHECK (char_length(comment) > 0),
    user_id BIGINT NOT NULL REFERENCES users(id),
    item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now()
);